name: Build and Deploy .NET Azure Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ScanFileFunction.sln

    - name: Build
      run: dotnet build ScanFileFunction.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ScanFileFunction/ScanFileFunction.csproj --configuration Release --output ./publish --no-build

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: scanfile-func
        package: ./publish
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
